server {
    listen 80;
    location /data/ {
        alias /usr/share/nginx/html/data/;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods GET;
    }
}
