services:

  stac-fastapi:
    image: ghcr.io/stac-utils/stac-fastapi-pgstac:5.0.2
#    restart: unless-stopped
    environment:
      # Postgres connection
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DB}
      - POSTGRES_HOST_READER=${POSTGRES_HOST_READER}
      - POSTGRES_HOST_WRITER=${POSTGRES_HOST_WRITER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DB_MIN_CONN_SIZE=${DB_MIN_CONN_SIZE}
      - DB_MAX_CONN_SIZE=${DB_MAX_CONN_SIZE}
      - STAC_API_KEY=${STAC_API_KEY}
    depends_on:
      - database
    command:
      bash -c "bash /tmp/scripts/wait-for-it.sh -t 120 -h database -p 5432 && uvicorn my_app:app --host 0.0.0.0 --port 8081"
    expose:
      - "8081"
    volumes:
      - ./dockerfiles/scripts:/tmp/scripts
      - ./my_app.py:/app/my_app.py
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  database:
    image: ghcr.io/stac-utils/pgstac:v0.9.6
#    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
    command: postgres -N 500
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  caddy:
    image: caddy:2.11.2
#    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dockerfiles/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./dockerfiles/caddy/caddy_data:/data
      - ./dockerfiles/caddy/caddy_config:/config
      - ${STAC_DATA_PATH}:/assets:ro
    depends_on:
      - stac-fastapi
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: eoapi-network
